pipeline {
    agent none
    options {
        disableResume()
    }
    stages {
        stage('Build') {
            agent { label 'build' }
            steps {
                script {
                    def filesInThisCommit = sh(script:"git diff --name-only HEAD~1..HEAD | grep '^cicd/jenkins-basic/'", returnStatus: false, returnStdout: true).split("\n")
                    echo "${filesInThisCommit}"
                    echo "${currentBuild.rawBuild.getCauses()[0].toString()}"
                    def hasChangesInPath = filesInThisCommit.size() > 0
                    if (!hasChangesInPath){
                        currentBuild.rawBuild.delete()
                        error("No changes detected in the path ('^cicd/jenkins-basic/')")
                    }
                }
                echo "Aborting all running jobs ..."
                script {
                    abortAllPreviousBuildInProgress(currentBuild)
                }
                echo "BRANCH_NAME:${env.BRANCH_NAME}\nCHANGE_ID:${env.CHANGE_ID}\nCHANGE_TARGET:${env.CHANGE_TARGET}"
                echo "Building ..."
                sh ".jenkins/pipeline-cli build --pr=${CHANGE_ID} --config=cicd/jenkins-basic/openshift/config.groovy"
            }
        }
        stage('Deploy (PROD)') {
            agent { label 'deploy' }
            input {
                message "Should we continue with deployment to PROD?"
                ok "Yes!"
            }
            steps {
                echo "Deploying ..."
                sh ".jenkins/pipeline-cli deploy --config=cicd/jenkins-basic/openshift/config.groovy --pr=${CHANGE_ID} --env=prod"
            }
        }
        stage('Acceptance') {
            agent { label 'deploy' }
            input {
                message "Should we continue with cleanup?"
                ok "Yes!"
            }
            steps {
                echo "Cleaning ..."
                sh ".jenkins/pipeline-cli cleanup --config=cicd/jenkins-basic/openshift/config.groovy --pr=${CHANGE_ID}"
            }
        }
    }
}