#!/usr/bin/env bash
OCP_PIPELINE_CLI_URL='https://raw.githubusercontent.com/BCDevOps/ocp-cd-pipeline/v0.0.5/src/main/resources/pipeline-cli'
OCP_PIPELINE_VERSION='0.0.5'

curl -sSL "${OCP_PIPELINE_CLI_URL}" | bash -s "$@"
