apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: jenkins-basic
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: rhel-atomic
    labels:
        shared: 'true'
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhel-atomic:7.5-408
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhel-atomic:7.5-408
      importPolicy: {}
      name: '7.5-408'
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
    labels:
        shared: 'true'
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    failedBuildsHistoryLimit: 2
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${VERSION}
    postCommit: {}
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    runPolicy: SerialLatestOnly
    source:
      contextDir: cicd/jenkins-basic/docker
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: rhel-atomic:7.5-408
      type: Docker
    successfulBuildsHistoryLimit: 2
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: jenkins-basic
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: ""
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v2-latest
- name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/BCDevOps/openshift-components.git
- name: SOURCE_REPOSITORY_REF
  required: false
  value: master
